services:
  app:
    build:
      context: ./TUBES PROTEIN BE/aplikasi-bidan-pintar
      dockerfile: Dockerfile
    container_name: bidanku-app
    working_dir: /usr/src/app
    volumes:
      - ./TUBES PROTEIN BE/aplikasi-bidan-pintar:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.docker
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: bidanku-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - app
      - vite
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: bidanku-db
    environment:
      MYSQL_DATABASE: bidanku
      MYSQL_ROOT_PASSWORD: bismillah
      MYSQL_USER: habb
      MYSQL_PASSWORD: 589654785
    volumes:
      - dbdata:/var/lib/mysql
      # Initialize database with existing SQL scripts
      - ./TUBES PROTEIN BE/aplikasi-bidan-pintar/database:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bidanku-pma
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: bismillah
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: bidanku-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network

  vite:
    build:
      context: ./TUBES PROTEIN FE
      dockerfile: Dockerfile
    container_name: bidanku-vite
    working_dir: /usr/src/app
    volumes:
      - ./TUBES PROTEIN FE:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - app
    networks:
      - app-network

volumes:
  dbdata:


networks:
  app-network:
    driver: bridge
